# Generated by Django 5.2.7 on 2026-09-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_thesis_timestamp_alter_thesis_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='degree',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
