# Generated by Django 5.2.7 on 2026-09-17 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_thesis_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='degree',
            field=models.CharField(choices=[('', '-Select Degree-'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('doctoral', 'Doctoral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_theses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('students', models.ManyToManyField(blank=True, related_name='students_institutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
