# Generated by Django 5.2.7 on 2026-09-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_thesis_degree_alter_thesis_student_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='students',
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.institution'),
        ),
    ]
