# Generated by Django 5.2.7 on 2026-09-23 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_subject_grade_subject_student_delete_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to='academics.teacher'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='degree',
            field=models.CharField(choices=[('', '-Select Degree-'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('doctoral', 'Doctoral'), ('other', 'Other')], max_length=20),
        ),
    ]
